Fix status code
redbitcz/merk-api-php pull request #7
Opened 2021-12-08 15:03 UTC by Dosty85

2021-12-08 15:12 UTC, jakubboucek requested changes
To se mi ale vůbec nelíbí. 204 by měla vracet úplně prázdné tělo, ale u nás vrací JSON se zprávou. Navíc slouží k něčemu jinému, třeba když pošleš POST, tak potvrzuje uložení dat. Ale pokud se nenajde žádná firma, tak by měl vracet 404. Jaký je důvod k této změně?

2021-12-08 19:29 UTC, Dosty85 commented
> To se mi ale vůbec nelíbí. 204 by měla vracet úplně prázdné tělo, ale u nás vrací JSON se zprávou. Navíc slouží k něčemu jinému, třeba když pošleš POST, tak potvrzuje uložení dat. Ale pokud se nenajde žádná firma, tak by měl vracet 404. Jaký je důvod k této změně?

404 je když stránka neexistuje. Ale u nás stránka existuje. Jen neexistuje záznam. Proto tam chci 204 No context. Přijde mi to přesnější. Neměl bych pak jak rozlišit jestli je chyba v URL, nebo v IČ.
Souhlasím, že by to mělo být bez těla. To mi nedošlo. A teď otázka. Trváš na 404? Nebo 204 bez těla?

2021-12-08 19:32 UTC, jakubboucek commented
> 404 je když stránka neexistuje. Ale u nás stránka existuje. Jen neexistuje záznam. Proto tam chci 204 No context. Přijde mi to přesnější. Neměl bych pak jak rozlišit jestli je chyba v URL, nebo v IČ.
> Souhlasím, že by to mělo být bez těla. To mi nedošlo. A teď otázka. Trváš na 404? Nebo 204 bez těla?

Bavíme se o API, dokonce o REST API.  Tam je 404 vlastnost. 

Chybu URL nebo tak něco pak poznáš z těla zprávy.

2021-12-09 12:16 UTC, Dosty85 commented
Ok, souhlasím. Dělal jsem si další návazný průzkum a opravdu 404 je korektní odpověď v tomto případě. Díky. Uzavírám,

2021-12-09 12:16 UTC, closed without merging